# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins:             [jekyll-paginate]

# Setup
title:               trayser.net
tagline:             ''
description:         'Made by <a href="https://twitter.com/trayser" target="_blank">@trayser</a>.'
url:                 http://trayser.net
baseurl:             ''
paginate:            5
tintcolor:          "#206888"

# About/contact
author:
  name:              Satyakam Khadilkar
  url:               https://twitter.com/trayser
  email:             raytracer@trayser.net

# Custom vars
version:             1.0.0
